/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ManagerSendEmailRouteImport } from './routes/manager.send-email'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerProjectsRouteImport } from './routes/manager.projects'
import { Route as ManagerPipelineRouteImport } from './routes/manager.pipeline'
import { Route as ManagerOffersRouteImport } from './routes/manager.offers'
import { Route as ManagerNotificationsRouteImport } from './routes/manager.notifications'
import { Route as ManagerLeadsRouteImport } from './routes/manager.leads'
import { Route as ManagerEmailInboxRouteImport } from './routes/manager.email-inbox'
import { Route as ManagerChatRouteImport } from './routes/manager.chat'
import { Route as ManagerAttendanceRouteImport } from './routes/manager.attendance'
import { Route as ManagerActivitiesRouteImport } from './routes/manager.activities'
import { Route as FinanceSendEmailRouteImport } from './routes/finance.send-email'
import { Route as FinanceNotificationsRouteImport } from './routes/finance.notifications'
import { Route as FinanceEmailInboxRouteImport } from './routes/finance.email-inbox'
import { Route as EmployeeSendEmailRouteImport } from './routes/employee.send-email'
import { Route as EmployeeProjectsRouteImport } from './routes/employee.projects'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeePipelineRouteImport } from './routes/employee.pipeline'
import { Route as EmployeeOffersRouteImport } from './routes/employee.offers'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee.notifications'
import { Route as EmployeeLeadsRouteImport } from './routes/employee.leads'
import { Route as EmployeeEmailInboxRouteImport } from './routes/employee.email-inbox'
import { Route as EmployeeChatRouteImport } from './routes/employee.chat'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee.attendance'
import { Route as EmployeeActivitiesRouteImport } from './routes/employee.activities'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminEmailInboxRouteImport } from './routes/admin.email-inbox'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as ManagerEmployeesIndexRouteImport } from './routes/manager.employees.index'
import { Route as ManagerProjectsProjectIdRouteImport } from './routes/manager.projects.$projectId'
import { Route as ManagerOffersQuotationIdRouteImport } from './routes/manager.offers.$quotationId'
import { Route as ManagerNotificationsSettingsRouteImport } from './routes/manager.notifications.settings'
import { Route as ManagerLeadsLeadIdRouteImport } from './routes/manager.leads.$leadId'
import { Route as ManagerEmployeesEmployeeIdRouteImport } from './routes/manager.employees.$employeeId'
import { Route as FinanceQuotationsQuotationIdRouteImport } from './routes/finance.quotations.$quotationId'
import { Route as FinanceNotificationsSettingsRouteImport } from './routes/finance.notifications.settings'
import { Route as FinanceLeadsLeadIdRouteImport } from './routes/finance.leads.$leadId'
import { Route as EmployeeOffersQuotationIdRouteImport } from './routes/employee.offers.$quotationId'
import { Route as EmployeeNotificationsSettingsRouteImport } from './routes/employee.notifications.settings'
import { Route as EmployeeLeadsLeadIdRouteImport } from './routes/employee.leads.$leadId'
import { Route as EmployeeActivitiesActivityIdRouteImport } from './routes/employee.activities.$activityId'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'
import { Route as AdminOffersQuotationIdRouteImport } from './routes/admin.offers.$quotationId'
import { Route as AdminNotificationsSettingsRouteImport } from './routes/admin.notifications.settings'
import { Route as AdminLeadsLeadIdRouteImport } from './routes/admin.leads.$leadId'
import { Route as AdminEmployeesEmployeeIdRouteImport } from './routes/admin.employees.$employeeId'
import { Route as AdminActivitiesActivityIdRouteImport } from './routes/admin.activities.$activityId'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerSendEmailRoute = ManagerSendEmailRouteImport.update({
  id: '/send-email',
  path: '/send-email',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerProjectsRoute = ManagerProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPipelineRoute = ManagerPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOffersRoute = ManagerOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerNotificationsRoute = ManagerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerLeadsRoute = ManagerLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerEmailInboxRoute = ManagerEmailInboxRouteImport.update({
  id: '/email-inbox',
  path: '/email-inbox',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerChatRoute = ManagerChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAttendanceRoute = ManagerAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerActivitiesRoute = ManagerActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => ManagerRoute,
} as any)
const FinanceSendEmailRoute = FinanceSendEmailRouteImport.update({
  id: '/send-email',
  path: '/send-email',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceNotificationsRoute = FinanceNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceEmailInboxRoute = FinanceEmailInboxRouteImport.update({
  id: '/email-inbox',
  path: '/email-inbox',
  getParentRoute: () => FinanceRoute,
} as any)
const EmployeeSendEmailRoute = EmployeeSendEmailRouteImport.update({
  id: '/send-email',
  path: '/send-email',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProjectsRoute = EmployeeProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePipelineRoute = EmployeePipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeOffersRoute = EmployeeOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeadsRoute = EmployeeLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeEmailInboxRoute = EmployeeEmailInboxRouteImport.update({
  id: '/email-inbox',
  path: '/email-inbox',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeChatRoute = EmployeeChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeActivitiesRoute = EmployeeActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailInboxRoute = AdminEmailInboxRouteImport.update({
  id: '/email-inbox',
  path: '/email-inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerEmployeesIndexRoute = ManagerEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerProjectsProjectIdRoute =
  ManagerProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => ManagerProjectsRoute,
  } as any)
const ManagerOffersQuotationIdRoute =
  ManagerOffersQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => ManagerOffersRoute,
  } as any)
const ManagerNotificationsSettingsRoute =
  ManagerNotificationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ManagerNotificationsRoute,
  } as any)
const ManagerLeadsLeadIdRoute = ManagerLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => ManagerLeadsRoute,
} as any)
const ManagerEmployeesEmployeeIdRoute =
  ManagerEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => ManagerRoute,
  } as any)
const FinanceQuotationsQuotationIdRoute =
  FinanceQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => FinanceRoute,
  } as any)
const FinanceNotificationsSettingsRoute =
  FinanceNotificationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => FinanceNotificationsRoute,
  } as any)
const FinanceLeadsLeadIdRoute = FinanceLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => FinanceRoute,
} as any)
const EmployeeOffersQuotationIdRoute =
  EmployeeOffersQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => EmployeeOffersRoute,
  } as any)
const EmployeeNotificationsSettingsRoute =
  EmployeeNotificationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => EmployeeNotificationsRoute,
  } as any)
const EmployeeLeadsLeadIdRoute = EmployeeLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => EmployeeLeadsRoute,
} as any)
const EmployeeActivitiesActivityIdRoute =
  EmployeeActivitiesActivityIdRouteImport.update({
    id: '/$activityId',
    path: '/$activityId',
    getParentRoute: () => EmployeeActivitiesRoute,
  } as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminOffersQuotationIdRoute = AdminOffersQuotationIdRouteImport.update({
  id: '/$quotationId',
  path: '/$quotationId',
  getParentRoute: () => AdminOffersRoute,
} as any)
const AdminNotificationsSettingsRoute =
  AdminNotificationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminNotificationsRoute,
  } as any)
const AdminLeadsLeadIdRoute = AdminLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminEmployeesEmployeeIdRoute =
  AdminEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AdminEmployeesRoute,
  } as any)
const AdminActivitiesActivityIdRoute =
  AdminActivitiesActivityIdRouteImport.update({
    id: '/$activityId',
    path: '/$activityId',
    getParentRoute: () => AdminActivitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/email-inbox': typeof AdminEmailInboxRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRouteWithChildren
  '/admin/offers': typeof AdminOffersRouteWithChildren
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/employee/activities': typeof EmployeeActivitiesRouteWithChildren
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/chat': typeof EmployeeChatRoute
  '/employee/email-inbox': typeof EmployeeEmailInboxRoute
  '/employee/leads': typeof EmployeeLeadsRouteWithChildren
  '/employee/notifications': typeof EmployeeNotificationsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRouteWithChildren
  '/employee/pipeline': typeof EmployeePipelineRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/employee/send-email': typeof EmployeeSendEmailRoute
  '/finance/email-inbox': typeof FinanceEmailInboxRoute
  '/finance/notifications': typeof FinanceNotificationsRouteWithChildren
  '/finance/send-email': typeof FinanceSendEmailRoute
  '/manager/activities': typeof ManagerActivitiesRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/chat': typeof ManagerChatRoute
  '/manager/email-inbox': typeof ManagerEmailInboxRoute
  '/manager/leads': typeof ManagerLeadsRouteWithChildren
  '/manager/notifications': typeof ManagerNotificationsRouteWithChildren
  '/manager/offers': typeof ManagerOffersRouteWithChildren
  '/manager/pipeline': typeof ManagerPipelineRoute
  '/manager/projects': typeof ManagerProjectsRouteWithChildren
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/send-email': typeof ManagerSendEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/admin/activities/$activityId': typeof AdminActivitiesActivityIdRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/notifications/settings': typeof AdminNotificationsSettingsRoute
  '/admin/offers/$quotationId': typeof AdminOffersQuotationIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/employee/activities/$activityId': typeof EmployeeActivitiesActivityIdRoute
  '/employee/leads/$leadId': typeof EmployeeLeadsLeadIdRoute
  '/employee/notifications/settings': typeof EmployeeNotificationsSettingsRoute
  '/employee/offers/$quotationId': typeof EmployeeOffersQuotationIdRoute
  '/finance/leads/$leadId': typeof FinanceLeadsLeadIdRoute
  '/finance/notifications/settings': typeof FinanceNotificationsSettingsRoute
  '/finance/quotations/$quotationId': typeof FinanceQuotationsQuotationIdRoute
  '/manager/employees/$employeeId': typeof ManagerEmployeesEmployeeIdRoute
  '/manager/leads/$leadId': typeof ManagerLeadsLeadIdRoute
  '/manager/notifications/settings': typeof ManagerNotificationsSettingsRoute
  '/manager/offers/$quotationId': typeof ManagerOffersQuotationIdRoute
  '/manager/projects/$projectId': typeof ManagerProjectsProjectIdRoute
  '/manager/employees/': typeof ManagerEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activities': typeof AdminActivitiesRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/email-inbox': typeof AdminEmailInboxRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRouteWithChildren
  '/admin/offers': typeof AdminOffersRouteWithChildren
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/employee/activities': typeof EmployeeActivitiesRouteWithChildren
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/chat': typeof EmployeeChatRoute
  '/employee/email-inbox': typeof EmployeeEmailInboxRoute
  '/employee/leads': typeof EmployeeLeadsRouteWithChildren
  '/employee/notifications': typeof EmployeeNotificationsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRouteWithChildren
  '/employee/pipeline': typeof EmployeePipelineRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/employee/send-email': typeof EmployeeSendEmailRoute
  '/finance/email-inbox': typeof FinanceEmailInboxRoute
  '/finance/notifications': typeof FinanceNotificationsRouteWithChildren
  '/finance/send-email': typeof FinanceSendEmailRoute
  '/manager/activities': typeof ManagerActivitiesRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/chat': typeof ManagerChatRoute
  '/manager/email-inbox': typeof ManagerEmailInboxRoute
  '/manager/leads': typeof ManagerLeadsRouteWithChildren
  '/manager/notifications': typeof ManagerNotificationsRouteWithChildren
  '/manager/offers': typeof ManagerOffersRouteWithChildren
  '/manager/pipeline': typeof ManagerPipelineRoute
  '/manager/projects': typeof ManagerProjectsRouteWithChildren
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/send-email': typeof ManagerSendEmailRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/admin/activities/$activityId': typeof AdminActivitiesActivityIdRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/notifications/settings': typeof AdminNotificationsSettingsRoute
  '/admin/offers/$quotationId': typeof AdminOffersQuotationIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/employee/activities/$activityId': typeof EmployeeActivitiesActivityIdRoute
  '/employee/leads/$leadId': typeof EmployeeLeadsLeadIdRoute
  '/employee/notifications/settings': typeof EmployeeNotificationsSettingsRoute
  '/employee/offers/$quotationId': typeof EmployeeOffersQuotationIdRoute
  '/finance/leads/$leadId': typeof FinanceLeadsLeadIdRoute
  '/finance/notifications/settings': typeof FinanceNotificationsSettingsRoute
  '/finance/quotations/$quotationId': typeof FinanceQuotationsQuotationIdRoute
  '/manager/employees/$employeeId': typeof ManagerEmployeesEmployeeIdRoute
  '/manager/leads/$leadId': typeof ManagerLeadsLeadIdRoute
  '/manager/notifications/settings': typeof ManagerNotificationsSettingsRoute
  '/manager/offers/$quotationId': typeof ManagerOffersQuotationIdRoute
  '/manager/projects/$projectId': typeof ManagerProjectsProjectIdRoute
  '/manager/employees': typeof ManagerEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/email-inbox': typeof AdminEmailInboxRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/history': typeof AdminHistoryRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRouteWithChildren
  '/admin/offers': typeof AdminOffersRouteWithChildren
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/employee/activities': typeof EmployeeActivitiesRouteWithChildren
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/chat': typeof EmployeeChatRoute
  '/employee/email-inbox': typeof EmployeeEmailInboxRoute
  '/employee/leads': typeof EmployeeLeadsRouteWithChildren
  '/employee/notifications': typeof EmployeeNotificationsRouteWithChildren
  '/employee/offers': typeof EmployeeOffersRouteWithChildren
  '/employee/pipeline': typeof EmployeePipelineRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/projects': typeof EmployeeProjectsRoute
  '/employee/send-email': typeof EmployeeSendEmailRoute
  '/finance/email-inbox': typeof FinanceEmailInboxRoute
  '/finance/notifications': typeof FinanceNotificationsRouteWithChildren
  '/finance/send-email': typeof FinanceSendEmailRoute
  '/manager/activities': typeof ManagerActivitiesRoute
  '/manager/attendance': typeof ManagerAttendanceRoute
  '/manager/chat': typeof ManagerChatRoute
  '/manager/email-inbox': typeof ManagerEmailInboxRoute
  '/manager/leads': typeof ManagerLeadsRouteWithChildren
  '/manager/notifications': typeof ManagerNotificationsRouteWithChildren
  '/manager/offers': typeof ManagerOffersRouteWithChildren
  '/manager/pipeline': typeof ManagerPipelineRoute
  '/manager/projects': typeof ManagerProjectsRouteWithChildren
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/send-email': typeof ManagerSendEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/admin/activities/$activityId': typeof AdminActivitiesActivityIdRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/leads/$leadId': typeof AdminLeadsLeadIdRoute
  '/admin/notifications/settings': typeof AdminNotificationsSettingsRoute
  '/admin/offers/$quotationId': typeof AdminOffersQuotationIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/employee/activities/$activityId': typeof EmployeeActivitiesActivityIdRoute
  '/employee/leads/$leadId': typeof EmployeeLeadsLeadIdRoute
  '/employee/notifications/settings': typeof EmployeeNotificationsSettingsRoute
  '/employee/offers/$quotationId': typeof EmployeeOffersQuotationIdRoute
  '/finance/leads/$leadId': typeof FinanceLeadsLeadIdRoute
  '/finance/notifications/settings': typeof FinanceNotificationsSettingsRoute
  '/finance/quotations/$quotationId': typeof FinanceQuotationsQuotationIdRoute
  '/manager/employees/$employeeId': typeof ManagerEmployeesEmployeeIdRoute
  '/manager/leads/$leadId': typeof ManagerLeadsLeadIdRoute
  '/manager/notifications/settings': typeof ManagerNotificationsSettingsRoute
  '/manager/offers/$quotationId': typeof ManagerOffersQuotationIdRoute
  '/manager/projects/$projectId': typeof ManagerProjectsProjectIdRoute
  '/manager/employees/': typeof ManagerEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/employee'
    | '/finance'
    | '/manager'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/chat'
    | '/admin/clients'
    | '/admin/email-inbox'
    | '/admin/employees'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/activities'
    | '/employee/attendance'
    | '/employee/chat'
    | '/employee/email-inbox'
    | '/employee/leads'
    | '/employee/notifications'
    | '/employee/offers'
    | '/employee/pipeline'
    | '/employee/profile'
    | '/employee/projects'
    | '/employee/send-email'
    | '/finance/email-inbox'
    | '/finance/notifications'
    | '/finance/send-email'
    | '/manager/activities'
    | '/manager/attendance'
    | '/manager/chat'
    | '/manager/email-inbox'
    | '/manager/leads'
    | '/manager/notifications'
    | '/manager/offers'
    | '/manager/pipeline'
    | '/manager/projects'
    | '/manager/reports'
    | '/manager/send-email'
    | '/admin/'
    | '/employee/'
    | '/finance/'
    | '/manager/'
    | '/admin/activities/$activityId'
    | '/admin/employees/$employeeId'
    | '/admin/leads/$leadId'
    | '/admin/notifications/settings'
    | '/admin/offers/$quotationId'
    | '/admin/projects/$projectId'
    | '/employee/activities/$activityId'
    | '/employee/leads/$leadId'
    | '/employee/notifications/settings'
    | '/employee/offers/$quotationId'
    | '/finance/leads/$leadId'
    | '/finance/notifications/settings'
    | '/finance/quotations/$quotationId'
    | '/manager/employees/$employeeId'
    | '/manager/leads/$leadId'
    | '/manager/notifications/settings'
    | '/manager/offers/$quotationId'
    | '/manager/projects/$projectId'
    | '/manager/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/chat'
    | '/admin/clients'
    | '/admin/email-inbox'
    | '/admin/employees'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/activities'
    | '/employee/attendance'
    | '/employee/chat'
    | '/employee/email-inbox'
    | '/employee/leads'
    | '/employee/notifications'
    | '/employee/offers'
    | '/employee/pipeline'
    | '/employee/profile'
    | '/employee/projects'
    | '/employee/send-email'
    | '/finance/email-inbox'
    | '/finance/notifications'
    | '/finance/send-email'
    | '/manager/activities'
    | '/manager/attendance'
    | '/manager/chat'
    | '/manager/email-inbox'
    | '/manager/leads'
    | '/manager/notifications'
    | '/manager/offers'
    | '/manager/pipeline'
    | '/manager/projects'
    | '/manager/reports'
    | '/manager/send-email'
    | '/admin'
    | '/employee'
    | '/finance'
    | '/manager'
    | '/admin/activities/$activityId'
    | '/admin/employees/$employeeId'
    | '/admin/leads/$leadId'
    | '/admin/notifications/settings'
    | '/admin/offers/$quotationId'
    | '/admin/projects/$projectId'
    | '/employee/activities/$activityId'
    | '/employee/leads/$leadId'
    | '/employee/notifications/settings'
    | '/employee/offers/$quotationId'
    | '/finance/leads/$leadId'
    | '/finance/notifications/settings'
    | '/finance/quotations/$quotationId'
    | '/manager/employees/$employeeId'
    | '/manager/leads/$leadId'
    | '/manager/notifications/settings'
    | '/manager/offers/$quotationId'
    | '/manager/projects/$projectId'
    | '/manager/employees'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/employee'
    | '/finance'
    | '/manager'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/chat'
    | '/admin/clients'
    | '/admin/email-inbox'
    | '/admin/employees'
    | '/admin/history'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/activities'
    | '/employee/attendance'
    | '/employee/chat'
    | '/employee/email-inbox'
    | '/employee/leads'
    | '/employee/notifications'
    | '/employee/offers'
    | '/employee/pipeline'
    | '/employee/profile'
    | '/employee/projects'
    | '/employee/send-email'
    | '/finance/email-inbox'
    | '/finance/notifications'
    | '/finance/send-email'
    | '/manager/activities'
    | '/manager/attendance'
    | '/manager/chat'
    | '/manager/email-inbox'
    | '/manager/leads'
    | '/manager/notifications'
    | '/manager/offers'
    | '/manager/pipeline'
    | '/manager/projects'
    | '/manager/reports'
    | '/manager/send-email'
    | '/admin/'
    | '/employee/'
    | '/finance/'
    | '/manager/'
    | '/admin/activities/$activityId'
    | '/admin/employees/$employeeId'
    | '/admin/leads/$leadId'
    | '/admin/notifications/settings'
    | '/admin/offers/$quotationId'
    | '/admin/projects/$projectId'
    | '/employee/activities/$activityId'
    | '/employee/leads/$leadId'
    | '/employee/notifications/settings'
    | '/employee/offers/$quotationId'
    | '/finance/leads/$leadId'
    | '/finance/notifications/settings'
    | '/finance/quotations/$quotationId'
    | '/manager/employees/$employeeId'
    | '/manager/leads/$leadId'
    | '/manager/notifications/settings'
    | '/manager/offers/$quotationId'
    | '/manager/projects/$projectId'
    | '/manager/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/send-email': {
      id: '/manager/send-email'
      path: '/send-email'
      fullPath: '/manager/send-email'
      preLoaderRoute: typeof ManagerSendEmailRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/projects': {
      id: '/manager/projects'
      path: '/projects'
      fullPath: '/manager/projects'
      preLoaderRoute: typeof ManagerProjectsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/pipeline': {
      id: '/manager/pipeline'
      path: '/pipeline'
      fullPath: '/manager/pipeline'
      preLoaderRoute: typeof ManagerPipelineRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/offers': {
      id: '/manager/offers'
      path: '/offers'
      fullPath: '/manager/offers'
      preLoaderRoute: typeof ManagerOffersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/notifications': {
      id: '/manager/notifications'
      path: '/notifications'
      fullPath: '/manager/notifications'
      preLoaderRoute: typeof ManagerNotificationsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/leads': {
      id: '/manager/leads'
      path: '/leads'
      fullPath: '/manager/leads'
      preLoaderRoute: typeof ManagerLeadsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/email-inbox': {
      id: '/manager/email-inbox'
      path: '/email-inbox'
      fullPath: '/manager/email-inbox'
      preLoaderRoute: typeof ManagerEmailInboxRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/chat': {
      id: '/manager/chat'
      path: '/chat'
      fullPath: '/manager/chat'
      preLoaderRoute: typeof ManagerChatRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/attendance': {
      id: '/manager/attendance'
      path: '/attendance'
      fullPath: '/manager/attendance'
      preLoaderRoute: typeof ManagerAttendanceRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/activities': {
      id: '/manager/activities'
      path: '/activities'
      fullPath: '/manager/activities'
      preLoaderRoute: typeof ManagerActivitiesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/finance/send-email': {
      id: '/finance/send-email'
      path: '/send-email'
      fullPath: '/finance/send-email'
      preLoaderRoute: typeof FinanceSendEmailRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/notifications': {
      id: '/finance/notifications'
      path: '/notifications'
      fullPath: '/finance/notifications'
      preLoaderRoute: typeof FinanceNotificationsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/email-inbox': {
      id: '/finance/email-inbox'
      path: '/email-inbox'
      fullPath: '/finance/email-inbox'
      preLoaderRoute: typeof FinanceEmailInboxRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/employee/send-email': {
      id: '/employee/send-email'
      path: '/send-email'
      fullPath: '/employee/send-email'
      preLoaderRoute: typeof EmployeeSendEmailRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/projects': {
      id: '/employee/projects'
      path: '/projects'
      fullPath: '/employee/projects'
      preLoaderRoute: typeof EmployeeProjectsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/pipeline': {
      id: '/employee/pipeline'
      path: '/pipeline'
      fullPath: '/employee/pipeline'
      preLoaderRoute: typeof EmployeePipelineRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/offers': {
      id: '/employee/offers'
      path: '/offers'
      fullPath: '/employee/offers'
      preLoaderRoute: typeof EmployeeOffersRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/leads': {
      id: '/employee/leads'
      path: '/leads'
      fullPath: '/employee/leads'
      preLoaderRoute: typeof EmployeeLeadsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/email-inbox': {
      id: '/employee/email-inbox'
      path: '/email-inbox'
      fullPath: '/employee/email-inbox'
      preLoaderRoute: typeof EmployeeEmailInboxRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/chat': {
      id: '/employee/chat'
      path: '/chat'
      fullPath: '/employee/chat'
      preLoaderRoute: typeof EmployeeChatRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/activities': {
      id: '/employee/activities'
      path: '/activities'
      fullPath: '/employee/activities'
      preLoaderRoute: typeof EmployeeActivitiesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-inbox': {
      id: '/admin/email-inbox'
      path: '/email-inbox'
      fullPath: '/admin/email-inbox'
      preLoaderRoute: typeof AdminEmailInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/employees/': {
      id: '/manager/employees/'
      path: '/employees'
      fullPath: '/manager/employees/'
      preLoaderRoute: typeof ManagerEmployeesIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/projects/$projectId': {
      id: '/manager/projects/$projectId'
      path: '/$projectId'
      fullPath: '/manager/projects/$projectId'
      preLoaderRoute: typeof ManagerProjectsProjectIdRouteImport
      parentRoute: typeof ManagerProjectsRoute
    }
    '/manager/offers/$quotationId': {
      id: '/manager/offers/$quotationId'
      path: '/$quotationId'
      fullPath: '/manager/offers/$quotationId'
      preLoaderRoute: typeof ManagerOffersQuotationIdRouteImport
      parentRoute: typeof ManagerOffersRoute
    }
    '/manager/notifications/settings': {
      id: '/manager/notifications/settings'
      path: '/settings'
      fullPath: '/manager/notifications/settings'
      preLoaderRoute: typeof ManagerNotificationsSettingsRouteImport
      parentRoute: typeof ManagerNotificationsRoute
    }
    '/manager/leads/$leadId': {
      id: '/manager/leads/$leadId'
      path: '/$leadId'
      fullPath: '/manager/leads/$leadId'
      preLoaderRoute: typeof ManagerLeadsLeadIdRouteImport
      parentRoute: typeof ManagerLeadsRoute
    }
    '/manager/employees/$employeeId': {
      id: '/manager/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/manager/employees/$employeeId'
      preLoaderRoute: typeof ManagerEmployeesEmployeeIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/finance/quotations/$quotationId': {
      id: '/finance/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/finance/quotations/$quotationId'
      preLoaderRoute: typeof FinanceQuotationsQuotationIdRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/notifications/settings': {
      id: '/finance/notifications/settings'
      path: '/settings'
      fullPath: '/finance/notifications/settings'
      preLoaderRoute: typeof FinanceNotificationsSettingsRouteImport
      parentRoute: typeof FinanceNotificationsRoute
    }
    '/finance/leads/$leadId': {
      id: '/finance/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/finance/leads/$leadId'
      preLoaderRoute: typeof FinanceLeadsLeadIdRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/employee/offers/$quotationId': {
      id: '/employee/offers/$quotationId'
      path: '/$quotationId'
      fullPath: '/employee/offers/$quotationId'
      preLoaderRoute: typeof EmployeeOffersQuotationIdRouteImport
      parentRoute: typeof EmployeeOffersRoute
    }
    '/employee/notifications/settings': {
      id: '/employee/notifications/settings'
      path: '/settings'
      fullPath: '/employee/notifications/settings'
      preLoaderRoute: typeof EmployeeNotificationsSettingsRouteImport
      parentRoute: typeof EmployeeNotificationsRoute
    }
    '/employee/leads/$leadId': {
      id: '/employee/leads/$leadId'
      path: '/$leadId'
      fullPath: '/employee/leads/$leadId'
      preLoaderRoute: typeof EmployeeLeadsLeadIdRouteImport
      parentRoute: typeof EmployeeLeadsRoute
    }
    '/employee/activities/$activityId': {
      id: '/employee/activities/$activityId'
      path: '/$activityId'
      fullPath: '/employee/activities/$activityId'
      preLoaderRoute: typeof EmployeeActivitiesActivityIdRouteImport
      parentRoute: typeof EmployeeActivitiesRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/offers/$quotationId': {
      id: '/admin/offers/$quotationId'
      path: '/$quotationId'
      fullPath: '/admin/offers/$quotationId'
      preLoaderRoute: typeof AdminOffersQuotationIdRouteImport
      parentRoute: typeof AdminOffersRoute
    }
    '/admin/notifications/settings': {
      id: '/admin/notifications/settings'
      path: '/settings'
      fullPath: '/admin/notifications/settings'
      preLoaderRoute: typeof AdminNotificationsSettingsRouteImport
      parentRoute: typeof AdminNotificationsRoute
    }
    '/admin/leads/$leadId': {
      id: '/admin/leads/$leadId'
      path: '/$leadId'
      fullPath: '/admin/leads/$leadId'
      preLoaderRoute: typeof AdminLeadsLeadIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/employees/$employeeId': {
      id: '/admin/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/admin/employees/$employeeId'
      preLoaderRoute: typeof AdminEmployeesEmployeeIdRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/activities/$activityId': {
      id: '/admin/activities/$activityId'
      path: '/$activityId'
      fullPath: '/admin/activities/$activityId'
      preLoaderRoute: typeof AdminActivitiesActivityIdRouteImport
      parentRoute: typeof AdminActivitiesRoute
    }
  }
}

interface AdminActivitiesRouteChildren {
  AdminActivitiesActivityIdRoute: typeof AdminActivitiesActivityIdRoute
}

const AdminActivitiesRouteChildren: AdminActivitiesRouteChildren = {
  AdminActivitiesActivityIdRoute: AdminActivitiesActivityIdRoute,
}

const AdminActivitiesRouteWithChildren = AdminActivitiesRoute._addFileChildren(
  AdminActivitiesRouteChildren,
)

interface AdminEmployeesRouteChildren {
  AdminEmployeesEmployeeIdRoute: typeof AdminEmployeesEmployeeIdRoute
}

const AdminEmployeesRouteChildren: AdminEmployeesRouteChildren = {
  AdminEmployeesEmployeeIdRoute: AdminEmployeesEmployeeIdRoute,
}

const AdminEmployeesRouteWithChildren = AdminEmployeesRoute._addFileChildren(
  AdminEmployeesRouteChildren,
)

interface AdminLeadsRouteChildren {
  AdminLeadsLeadIdRoute: typeof AdminLeadsLeadIdRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsLeadIdRoute: AdminLeadsLeadIdRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminNotificationsRouteChildren {
  AdminNotificationsSettingsRoute: typeof AdminNotificationsSettingsRoute
}

const AdminNotificationsRouteChildren: AdminNotificationsRouteChildren = {
  AdminNotificationsSettingsRoute: AdminNotificationsSettingsRoute,
}

const AdminNotificationsRouteWithChildren =
  AdminNotificationsRoute._addFileChildren(AdminNotificationsRouteChildren)

interface AdminOffersRouteChildren {
  AdminOffersQuotationIdRoute: typeof AdminOffersQuotationIdRoute
}

const AdminOffersRouteChildren: AdminOffersRouteChildren = {
  AdminOffersQuotationIdRoute: AdminOffersQuotationIdRoute,
}

const AdminOffersRouteWithChildren = AdminOffersRoute._addFileChildren(
  AdminOffersRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRouteWithChildren
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminEmailInboxRoute: typeof AdminEmailInboxRoute
  AdminEmployeesRoute: typeof AdminEmployeesRouteWithChildren
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRouteWithChildren
  AdminOffersRoute: typeof AdminOffersRouteWithChildren
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRouteWithChildren,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminChatRoute: AdminChatRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminEmailInboxRoute: AdminEmailInboxRoute,
  AdminEmployeesRoute: AdminEmployeesRouteWithChildren,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRouteWithChildren,
  AdminOffersRoute: AdminOffersRouteWithChildren,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeActivitiesRouteChildren {
  EmployeeActivitiesActivityIdRoute: typeof EmployeeActivitiesActivityIdRoute
}

const EmployeeActivitiesRouteChildren: EmployeeActivitiesRouteChildren = {
  EmployeeActivitiesActivityIdRoute: EmployeeActivitiesActivityIdRoute,
}

const EmployeeActivitiesRouteWithChildren =
  EmployeeActivitiesRoute._addFileChildren(EmployeeActivitiesRouteChildren)

interface EmployeeLeadsRouteChildren {
  EmployeeLeadsLeadIdRoute: typeof EmployeeLeadsLeadIdRoute
}

const EmployeeLeadsRouteChildren: EmployeeLeadsRouteChildren = {
  EmployeeLeadsLeadIdRoute: EmployeeLeadsLeadIdRoute,
}

const EmployeeLeadsRouteWithChildren = EmployeeLeadsRoute._addFileChildren(
  EmployeeLeadsRouteChildren,
)

interface EmployeeNotificationsRouteChildren {
  EmployeeNotificationsSettingsRoute: typeof EmployeeNotificationsSettingsRoute
}

const EmployeeNotificationsRouteChildren: EmployeeNotificationsRouteChildren = {
  EmployeeNotificationsSettingsRoute: EmployeeNotificationsSettingsRoute,
}

const EmployeeNotificationsRouteWithChildren =
  EmployeeNotificationsRoute._addFileChildren(
    EmployeeNotificationsRouteChildren,
  )

interface EmployeeOffersRouteChildren {
  EmployeeOffersQuotationIdRoute: typeof EmployeeOffersQuotationIdRoute
}

const EmployeeOffersRouteChildren: EmployeeOffersRouteChildren = {
  EmployeeOffersQuotationIdRoute: EmployeeOffersQuotationIdRoute,
}

const EmployeeOffersRouteWithChildren = EmployeeOffersRoute._addFileChildren(
  EmployeeOffersRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeActivitiesRoute: typeof EmployeeActivitiesRouteWithChildren
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeChatRoute: typeof EmployeeChatRoute
  EmployeeEmailInboxRoute: typeof EmployeeEmailInboxRoute
  EmployeeLeadsRoute: typeof EmployeeLeadsRouteWithChildren
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRouteWithChildren
  EmployeeOffersRoute: typeof EmployeeOffersRouteWithChildren
  EmployeePipelineRoute: typeof EmployeePipelineRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeProjectsRoute: typeof EmployeeProjectsRoute
  EmployeeSendEmailRoute: typeof EmployeeSendEmailRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeActivitiesRoute: EmployeeActivitiesRouteWithChildren,
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeChatRoute: EmployeeChatRoute,
  EmployeeEmailInboxRoute: EmployeeEmailInboxRoute,
  EmployeeLeadsRoute: EmployeeLeadsRouteWithChildren,
  EmployeeNotificationsRoute: EmployeeNotificationsRouteWithChildren,
  EmployeeOffersRoute: EmployeeOffersRouteWithChildren,
  EmployeePipelineRoute: EmployeePipelineRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeProjectsRoute: EmployeeProjectsRoute,
  EmployeeSendEmailRoute: EmployeeSendEmailRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface FinanceNotificationsRouteChildren {
  FinanceNotificationsSettingsRoute: typeof FinanceNotificationsSettingsRoute
}

const FinanceNotificationsRouteChildren: FinanceNotificationsRouteChildren = {
  FinanceNotificationsSettingsRoute: FinanceNotificationsSettingsRoute,
}

const FinanceNotificationsRouteWithChildren =
  FinanceNotificationsRoute._addFileChildren(FinanceNotificationsRouteChildren)

interface FinanceRouteChildren {
  FinanceEmailInboxRoute: typeof FinanceEmailInboxRoute
  FinanceNotificationsRoute: typeof FinanceNotificationsRouteWithChildren
  FinanceSendEmailRoute: typeof FinanceSendEmailRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  FinanceLeadsLeadIdRoute: typeof FinanceLeadsLeadIdRoute
  FinanceQuotationsQuotationIdRoute: typeof FinanceQuotationsQuotationIdRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceEmailInboxRoute: FinanceEmailInboxRoute,
  FinanceNotificationsRoute: FinanceNotificationsRouteWithChildren,
  FinanceSendEmailRoute: FinanceSendEmailRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  FinanceLeadsLeadIdRoute: FinanceLeadsLeadIdRoute,
  FinanceQuotationsQuotationIdRoute: FinanceQuotationsQuotationIdRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface ManagerLeadsRouteChildren {
  ManagerLeadsLeadIdRoute: typeof ManagerLeadsLeadIdRoute
}

const ManagerLeadsRouteChildren: ManagerLeadsRouteChildren = {
  ManagerLeadsLeadIdRoute: ManagerLeadsLeadIdRoute,
}

const ManagerLeadsRouteWithChildren = ManagerLeadsRoute._addFileChildren(
  ManagerLeadsRouteChildren,
)

interface ManagerNotificationsRouteChildren {
  ManagerNotificationsSettingsRoute: typeof ManagerNotificationsSettingsRoute
}

const ManagerNotificationsRouteChildren: ManagerNotificationsRouteChildren = {
  ManagerNotificationsSettingsRoute: ManagerNotificationsSettingsRoute,
}

const ManagerNotificationsRouteWithChildren =
  ManagerNotificationsRoute._addFileChildren(ManagerNotificationsRouteChildren)

interface ManagerOffersRouteChildren {
  ManagerOffersQuotationIdRoute: typeof ManagerOffersQuotationIdRoute
}

const ManagerOffersRouteChildren: ManagerOffersRouteChildren = {
  ManagerOffersQuotationIdRoute: ManagerOffersQuotationIdRoute,
}

const ManagerOffersRouteWithChildren = ManagerOffersRoute._addFileChildren(
  ManagerOffersRouteChildren,
)

interface ManagerProjectsRouteChildren {
  ManagerProjectsProjectIdRoute: typeof ManagerProjectsProjectIdRoute
}

const ManagerProjectsRouteChildren: ManagerProjectsRouteChildren = {
  ManagerProjectsProjectIdRoute: ManagerProjectsProjectIdRoute,
}

const ManagerProjectsRouteWithChildren = ManagerProjectsRoute._addFileChildren(
  ManagerProjectsRouteChildren,
)

interface ManagerRouteChildren {
  ManagerActivitiesRoute: typeof ManagerActivitiesRoute
  ManagerAttendanceRoute: typeof ManagerAttendanceRoute
  ManagerChatRoute: typeof ManagerChatRoute
  ManagerEmailInboxRoute: typeof ManagerEmailInboxRoute
  ManagerLeadsRoute: typeof ManagerLeadsRouteWithChildren
  ManagerNotificationsRoute: typeof ManagerNotificationsRouteWithChildren
  ManagerOffersRoute: typeof ManagerOffersRouteWithChildren
  ManagerPipelineRoute: typeof ManagerPipelineRoute
  ManagerProjectsRoute: typeof ManagerProjectsRouteWithChildren
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerSendEmailRoute: typeof ManagerSendEmailRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerEmployeesEmployeeIdRoute: typeof ManagerEmployeesEmployeeIdRoute
  ManagerEmployeesIndexRoute: typeof ManagerEmployeesIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerActivitiesRoute: ManagerActivitiesRoute,
  ManagerAttendanceRoute: ManagerAttendanceRoute,
  ManagerChatRoute: ManagerChatRoute,
  ManagerEmailInboxRoute: ManagerEmailInboxRoute,
  ManagerLeadsRoute: ManagerLeadsRouteWithChildren,
  ManagerNotificationsRoute: ManagerNotificationsRouteWithChildren,
  ManagerOffersRoute: ManagerOffersRouteWithChildren,
  ManagerPipelineRoute: ManagerPipelineRoute,
  ManagerProjectsRoute: ManagerProjectsRouteWithChildren,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerSendEmailRoute: ManagerSendEmailRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerEmployeesEmployeeIdRoute: ManagerEmployeesEmployeeIdRoute,
  ManagerEmployeesIndexRoute: ManagerEmployeesIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
